apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dvoj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dvoj
    app.kubernetes.io/part-of: tkrw-pr714-0075-0051-app
  name: devfile-sample-dvoj
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-dvoj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-dvoj
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0051-tenant/tkrw-pr714-0075-0051-app/devfile-sample-dvoj@sha256:6ebdb757fac4d9c2099bdbcb47a2f6f6a3b6686ad5a4140e44dfa12e62c50f73
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
